import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)
from reportlab.lib.enums import TA_CENTER

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="ReportTitle", fontSize=18, leading=22, alignment=TA_CENTER,
                           textColor=colors.HexColor("#1a237e"), spaceAfter=6))
styles.add(ParagraphStyle(name="SectionHeading", fontSize=13, leading=16,
                           textColor=colors.white, backColor=colors.HexColor("#3f51b5"),
                           spaceBefore=10, spaceAfter=6, leftIndent=4, borderPadding=4))
styles.add(ParagraphStyle(name="Small", fontSize=9, textColor=colors.grey))
styles.add(ParagraphStyle(name="QBody", fontSize=10, leading=14))


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(20 * mm, 10 * mm, "Generated by Exam Portal")
    canvas.drawRightString(190 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_result_pdf(attempt, output_folder):
    """Builds a full result + answer-sheet PDF for a submitted attempt.
    Returns the absolute file path.
    """
    os.makedirs(output_folder, exist_ok=True)
    student = attempt.student
    exam = attempt.exam
    result = attempt.result

    filename = f"result_{attempt.id}_{student.id}.pdf"
    filepath = os.path.join(output_folder, filename)

    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm, leftMargin=18 * mm, rightMargin=18 * mm,
    )
    story = []

    story.append(Paragraph("EXAM PORTAL", styles["ReportTitle"]))
    story.append(Paragraph("Official Exam Result Report", styles["Small"]))
    story.append(Spacer(1, 10))

    # Student details
    story.append(Paragraph("Student Details", styles["SectionHeading"]))
    student_data = [
        ["Full Name", student.full_name, "Email", student.email],
        ["Phone", student.phone, "College", student.college or "-"],
        ["City", student.city or "-", "Attempt ID", str(attempt.id)],
    ]
    t = Table(student_data, colWidths=[35 * mm, 55 * mm, 30 * mm, 50 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eeeeee")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#eeeeee")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t)
    story.append(Spacer(1, 8))

    # Exam details & score summary
    story.append(Paragraph("Exam & Score Summary", styles["SectionHeading"]))
    pct = result.percentage if result else 0
    status = (result.status if result else "-").upper()
    status_color = colors.HexColor("#2e7d32") if status == "PASS" else colors.HexColor("#c62828")

    summary_data = [
        ["Exam Name", exam.title, "Status", status],
        ["Total Questions", str(result.total_questions if result else 0),
         "Attempted", str(result.attempted if result else 0)],
        ["Correct", str(result.correct if result else 0),
         "Wrong", str(result.wrong if result else 0)],
        ["Skipped", str(result.skipped if result else 0),
         "Score", f"{result.score if result else 0} / {result.total_marks if result else 0}"],
        ["Percentage", f"{pct}%",
         "Time Taken", _fmt_seconds(result.time_taken_seconds if result else 0)],
    ]
    t2 = Table(summary_data, colWidths=[35 * mm, 55 * mm, 30 * mm, 50 * mm])
    style_cmds = [
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eeeeee")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#eeeeee")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TEXTCOLOR", (3, 0), (3, 0), status_color),
        ("FONTNAME", (3, 0), (3, 0), "Helvetica-Bold"),
    ]
    t2.setStyle(TableStyle(style_cmds))
    story.append(t2)
    story.append(Spacer(1, 10))

    # Answer sheet
    story.append(Paragraph("Question-Wise Answer Review", styles["SectionHeading"]))
    answers = {a.question_id: a for a in attempt.answers}

    for idx, q in enumerate(exam.questions, start=1):
        ans = answers.get(q.id)
        student_ans_text = _format_student_answer(q, ans)
        correct_ans_text = _format_correct_answer(q)

        if ans is None or ans.is_correct is None:
            verdict, verdict_color, verdict_hex = "SKIPPED", colors.grey, "#757575"
        elif ans.is_correct:
            verdict, verdict_color, verdict_hex = "CORRECT", colors.HexColor("#2e7d32"), "#2e7d32"
        else:
            verdict, verdict_color, verdict_hex = "WRONG", colors.HexColor("#c62828"), "#c62828"

        q_data = [
            [Paragraph(f"<b>Q{idx}.</b> {q.question_text}", styles["QBody"])],
            [Paragraph(f"Your Answer: {student_ans_text}", styles["QBody"])],
            [Paragraph(f"Correct Answer: {correct_ans_text}", styles["QBody"])],
        ]
        if q.explanation:
            q_data.append([Paragraph(f"Explanation: {q.explanation}", styles["Small"])])

        qt = Table(q_data, colWidths=[170 * mm])
        qt.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.6, verdict_color),
            ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#f5f5f5")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(qt)
        story.append(Paragraph(f"<font color='{verdict_hex}'><b>{verdict}</b>"
                                f" &nbsp; | &nbsp; Marks: {ans.marks_awarded if ans else 0}</font>", styles["Small"]))
        story.append(Spacer(1, 6))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return filepath


def _fmt_seconds(total_seconds):
    total_seconds = total_seconds or 0
    m, s = divmod(int(total_seconds), 60)
    h, m = divmod(m, 60)
    if h:
        return f"{h}h {m}m {s}s"
    return f"{m}m {s}s"


def _format_student_answer(question, answer):
    if answer is None:
        return "Not Answered"
    if question.question_type in ("single_choice", "true_false", "image_based", "multiple_choice",
                                   "paragraph", "case_study"):
        ids = answer.selected_ids_list()
        if not ids:
            return "Not Answered"
        opts = {o.id: o.option_text for o in question.options}
        return ", ".join(opts.get(i, "?") for i in ids)
    if question.question_type == "integer":
        return str(answer.integer_answer) if answer.integer_answer is not None else "Not Answered"
    if question.question_type == "fill_blank":
        return answer.text_answer or "Not Answered"
    return "Not Answered"


def _format_correct_answer(question):
    if question.question_type in ("single_choice", "true_false", "image_based", "multiple_choice",
                                   "paragraph", "case_study"):
        correct = [o.option_text for o in question.options if o.is_correct]
        return ", ".join(correct) if correct else "-"
    if question.question_type == "integer":
        return str(question.correct_integer_answer)
    if question.question_type == "fill_blank":
        return question.correct_text_answer or "-"
    return "-"


# --------------------------------------------------------------------------
# Student list export (Module 4) - all / single college / selected students
# --------------------------------------------------------------------------
def generate_students_list_pdf(rows, output_path, title="Student List"):
    """rows: list of dicts with keys name, college, email, phone, address,
    registered, exam_count, avg_score, best_score, subscription."""
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        topMargin=15 * mm, bottomMargin=15 * mm, leftMargin=12 * mm, rightMargin=12 * mm,
    )
    story = [
        Paragraph("EXAM PORTAL", styles["ReportTitle"]),
        Paragraph(title, styles["Small"]),
        Spacer(1, 10),
    ]

    header = ["Name", "College", "Email", "Phone", "Registered", "Exams", "Avg %", "Best %", "Subscription"]
    data = [header]
    for r in rows:
        data.append([
            r.get("name", ""), r.get("college", "") or "-", r.get("email", ""), r.get("phone", ""),
            r.get("registered", ""), str(r.get("exam_count", 0)),
            str(r.get("avg_score", 0)), str(r.get("best_score", 0)), r.get("subscription", "-"),
        ])

    t = Table(data, repeatRows=1, colWidths=[26 * mm, 26 * mm, 38 * mm, 20 * mm, 18 * mm, 12 * mm, 12 * mm, 12 * mm, 22 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3f51b5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f8fc")]),
    ]))
    story.append(t)
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')} &nbsp;|&nbsp; Total: {len(rows)} student(s)", styles["Small"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return output_path


# --------------------------------------------------------------------------
# Invoice PDF (Module 10)
# --------------------------------------------------------------------------
def generate_invoice_pdf(purchase, output_path):
    student = purchase.student
    course = purchase.course

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm, leftMargin=18 * mm, rightMargin=18 * mm,
    )
    story = [
        Paragraph("EXAM PORTAL", styles["ReportTitle"]),
        Paragraph("Payment Invoice", styles["Small"]),
        Spacer(1, 12),
    ]

    info = [
        ["Invoice No.", purchase.invoice_number or "-", "Date", (purchase.verified_at or purchase.created_at).strftime("%d %b %Y")],
        ["Student", student.full_name, "College", student.college_name],
        ["Email", student.email, "Phone", student.phone],
    ]
    t1 = Table(info, colWidths=[28 * mm, 62 * mm, 25 * mm, 55 * mm])
    t1.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eeeeee")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#eeeeee")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t1)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Course Purchased", styles["SectionHeading"]))
    course_data = [
        ["Course", "Duration", "Amount Paid", "Status", "Reference"],
        [course.title, course.duration_label or "-", f"Rs. {purchase.amount:.2f}",
         purchase.status.upper(), purchase.student_txn_id or purchase.reference_code],
    ]
    t2 = Table(course_data, colWidths=[55 * mm, 30 * mm, 30 * mm, 25 * mm, 30 * mm])
    t2.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3f51b5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t2)
    story.append(Spacer(1, 10))

    # Amount breakdown - only shown when there's something to break down
    # (discount / GST / platform fee), so a plain purchase's invoice stays
    # as simple as before. Mirrors the checkout page breakdown exactly, and
    # is why original_amount/discount_amount/tax_amount/platform_fee_amount
    # are all stored separately on the purchase rather than only the total.
    if (purchase.discount_amount or purchase.tax_amount or purchase.platform_fee_amount):
        story.append(Paragraph("Amount Breakdown", styles["SectionHeading"]))
        breakdown_rows = [["Plan Amount", f"Rs. {(purchase.original_amount or purchase.amount):.2f}"]]
        if purchase.discount_amount:
            coupon_label = f" ({purchase.coupon.code})" if purchase.coupon else ""
            breakdown_rows.append([f"Discount{coupon_label}", f"- Rs. {purchase.discount_amount:.2f}"])
        if purchase.tax_amount:
            breakdown_rows.append(["GST", f"Rs. {purchase.tax_amount:.2f}"])
        if purchase.platform_fee_amount:
            breakdown_rows.append(["Platform / Payment Convenience Fee", f"Rs. {purchase.platform_fee_amount:.2f}"])
        breakdown_rows.append(["Total Paid", f"Rs. {purchase.amount:.2f}"])
        t3 = Table(breakdown_rows, colWidths=[100 * mm, 70 * mm])
        t3.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(t3)
        story.append(Spacer(1, 10))

    if purchase.expires_at:
        story.append(Paragraph(f"Subscription active until: <b>{purchase.expires_at.strftime('%d %b %Y')}</b>", styles["QBody"]))

    story.append(Spacer(1, 20))
    story.append(Paragraph("This is a system-generated invoice.", styles["Small"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return output_path


def generate_certificate_pdf(certificate, output_path):
    """Landscape completion certificate for the Certificates module.
    `certificate` is an IssuedCertificate row (student_account, course set)."""
    from reportlab.pdfgen import canvas as pdf_canvas
    from reportlab.lib.pagesizes import landscape

    student = certificate.student_account
    course = certificate.course

    page_w, page_h = landscape(A4)
    c = pdf_canvas.Canvas(output_path, pagesize=landscape(A4))

    # Border
    c.setStrokeColor(colors.HexColor("#1a237e"))
    c.setLineWidth(3)
    c.rect(12 * mm, 12 * mm, page_w - 24 * mm, page_h - 24 * mm)
    c.setLineWidth(1)
    c.rect(16 * mm, 16 * mm, page_w - 32 * mm, page_h - 32 * mm)

    c.setFont("Helvetica-Bold", 26)
    c.setFillColor(colors.HexColor("#1a237e"))
    c.drawCentredString(page_w / 2, page_h - 40 * mm, "CERTIFICATE OF COMPLETION")

    c.setFont("Helvetica", 12)
    c.setFillColor(colors.HexColor("#555555"))
    c.drawCentredString(page_w / 2, page_h - 52 * mm, "Kalyani Exam Hub proudly presents this certificate to")

    c.setFont("Helvetica-Bold", 30)
    c.setFillColor(colors.HexColor("#000000"))
    c.drawCentredString(page_w / 2, page_h - 68 * mm, student.full_name)

    c.setFont("Helvetica", 13)
    c.setFillColor(colors.HexColor("#333333"))
    c.drawCentredString(
        page_w / 2, page_h - 82 * mm,
        f"for successfully completing the course \"{course.title}\""
    )
    c.drawCentredString(
        page_w / 2, page_h - 90 * mm,
        f"with {certificate.completion_percent:.0f}% of the study material covered."
    )

    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#777777"))
    c.drawCentredString(page_w / 2, 32 * mm, f"Certificate No. {certificate.certificate_number}")
    c.drawCentredString(page_w / 2, 26 * mm, f"Issued on {certificate.issued_at.strftime('%d %B %Y')}")

    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1a237e"))
    c.drawCentredString(page_w / 2, 44 * mm, "Kalyani Exam Hub")

    c.showPage()
    c.save()
    return output_path
